### ISSUE TITLE
Scaling the audit table

### ISSUE THREAD

**Issue by MichaelDBA** [supabase/supa_audit#32]
The audit table can get quite large depending on how extensively it is used within a database.  Can you suggest any optimized ways to partition this table, i.e., what partition key to use, etc.  Or perhaps have multiple partition tables per group of tables, let's say within a particular schema?

**Comment by olirice** [comment]
> Can you suggest any optimized ways to partition this table

I haven't had experience with optimizing query performance at that scale yet, but `ts` seems like the easy choice for partitioning. Im not clear how we'd allow user configurability, or provide useful defaults, for partitioning with the table as part of an extension but its a good question

I'll leave this open in case others have ideas

**Comment by MichaelDBA** [comment]
thanks

**Comment by rallisf1** [comment]
I agree this needs partitioning to become relevant for large projects. A good practice would be to partition by table and sub-partition by year & month.

Partition creation can be automated:

### Partition by Table

  1. Create audit.record_version partitions for existing tables upon extension install
  2. Add a trigger for creating audit.record_version partitions on 'CREATE TABLE'
  
### Sub-partition by Year & Month

  1. Add a function that adds a partition to each existing audit.record_version.table_oid for the current month
  2. Chech if pg_cron is installed, only proceed if it's available
  3. Run the function upon extension install
  4. Schedule the function to run using pg_cron at the first day of each month (0 0 1 * *)

### Partition Naming Proposal

audit.record_version.table_oid.year.month

Example: audit.record_version.16328.2023.08

P.S. The sql code is very straight-forward but I haven't dealt with pg extensions before. I could really use a contributing guide.

**Comment by olirice** [comment]
this project is a convenient approach for maintain an audit history for low-mid volume tables for consumption within SQL. Past that use-case, we recommend logging based solutions that are more configurable like https://www.pgaudit.org

**Comment by olirice** [comment]
I'm going to close this issue as out-of-scope but you're welcome to continue the discussion to suggest partitioning strategies for e.g. forks or local use!

**Comment by rallisf1** [comment]
True, pgaudit is the better choice but I wanted something more practical for Actions Auditing for my app, not a full fledged db auditing, and this extension was a big step towards that.

Anyway, for whomever is concerned I have added partitioning in my [fork](https://github.com/rallisf1/supa_audit/blob/main/supa_audit--0.4.0.sql). This is a breaking change as you cannot add partitioning to an existing table, thus audit.record_version needs to be created from scratch. I guess you could rename the existing table and copy over the data.

The naming convention for the partitions is: audit.record_version_SCHEMA_TABLE_YEAR_MONTH e.g. `audit.record_version_public_account_2023_8` but since partition pruning is enabled by default you only need to query audit.record_version.

P.S. This isn't battle tested yet; I just forked it last night. Let me know if you need an update in a few months.
