### ISSUE TITLE
Record the `application_name` connection parameter 

### ISSUE THREAD

**Issue by paulovieira** [supabase/supa_audit#40]
# Feature request

## Is your feature request related to a problem? Please describe.

The `application_name` in the audit table can be useful to distinguish between changes made in different contexts (changes done by the end-user, using some user interface, vs changes done by some data migration)

> The application_name can be any string (...). It is typically set by an application upon connection to the server. The name will be displayed in the pg_stat_activity view and included in CSV log entries. 

https://www.postgresql.org/docs/current/runtime-config-logging.html#GUC-APPLICATION-NAME

## Describe the solution you'd like

1) add a new column
```sql
alter table audit.record_version
add column application_name TEXT;
```
2) in the `audit.insert_update_delete_trigger` trigger, call [`current_setting`](https://www.postgresql.org/docs/current/functions-admin.html#FUNCTIONS-ADMIN-SET)

```sql
    insert into audit.record_version(
        record_id,
        old_record_id,
        op,
        table_oid,
        table_schema,
        table_name,
        record,
        old_record,
        application_name
    )
    select
        record_id,
        old_record_id,
        TG_OP::audit.operation,
        TG_RELID,
        TG_TABLE_SCHEMA,
        TG_TABLE_NAME,
        record_jsonb,
        old_record_jsonb,
        current_setting('application_name', 't');
```

Thanks for considering this suggestion.

**Comment by olirice** [comment]
thanks @paulovieira, I can see why this feature would be useful

If you're interested in capturing this (or other) telemetry for each record, you can add column to `audit.record_version` and use a trigger to capture the `application_name` without modifying any code in `supa_audit`.

Given that theres a lot of context that users may want to capture, and we'd like to keep the main audit table a small as possible, I recommend using the approach ^ for this feature rather than upstreaming it here

If you do go that route I'd be happy to include the code snippet in the README under an `Extensibility` heading
