### ISSUE TITLE
Add supa_audit to extensions lib

### ISSUE THREAD

**Issue by jsbrain** [supabase/supa_audit#58]
Wondering why `supa_audit` is not pre-installed into the extensions library as `supautils` for example?

Would be a great addition imo ...

**Comment by olirice** [comment]
generally we promote pgaudit for real-world auditing needs. This project was a companion to a blog post that showed off some cool features of Postgres but pgaudit is much for feature full and scalable.

since this is a SQL only extension you can always install it yourself if you like keeping the audit trail available in the DB
