### ISSUE TITLE
A version that shows changes (diff) made by UPDATE operations.

### ISSUE THREAD

**Issue by GitTom** [supabase/supa_audit#64]
Here is a version of supa_audit with one additional feature:  it adds a column to the audit table that shows what changes were made by an UPDATE.

https://gist.github.com/GitTom/e178a61aa6b2b6e5ad92f15a36f4eb2e

I find useful during development to be able to easily see what was changed.

### Started from
Version 3.1 of Supabase Audit
https://github.com/supabase/supa_audit/blob/main/supa_audit--0.3.1.sql

### Applied pgFormatter.
made the keywords upper case

### Enable dependency
I added
`CREATE EXTENSION IF NOT EXISTS "uuid-ossp";`

### Additional column
For the audit log table - added a `changes` column

### Modified `insert_update_delete_trigger` function.
For UPDATE operations it uses `jsonb_object_agg()` and new `compare_json()` to calculate the changes.

Also, I got it ignore any column named `updated_at` since that will always change.   Maybe I should also get it to ignore computed columns?  Not sure about this.

### New function for JSON columns
New function compare_json() to find the changes in JSON columns.

## Notes
Tested on PostgreSQL 16.3
Most of the additional code written by an LLM.

**Comment by olirice** [comment]
very cool

I follow why you may want a diff summary. In relational DBs you generally don't want to store data that is a pure function of other inputs available in the db in order to maintain all facts with a single source of truth. You can read more about that concept here https://en.wikipedia.org/wiki/Boyce%E2%80%93Codd_normal_form

For that reason we're not likely to upstream the change.

Just out of interest, there are a couple of other ways you could accomplish that without storing computing it in the trigger 

- use a [generated column](https://www.postgresql.org/docs/current/ddl-generated-columns.html)
- create a view on top of the audit table that adds in the data

the first option is a operationally simpler but you do have to store the values on disk. The second option computes the diff on the fly for whichever records you're looking at but requires a secondary view

In any case, nice usability idea!

**Comment by GitTom** [comment]
Yes, I acknowledge your points.   

For me, this is just an informal convenience that I will use during development.  To that end, it's enough for me that it works and is useful.  

And I do find that something that shows me what changed - including what exactly changed in JSON columns rather than just which columns were updated - to be very useful!

I figured that it would not be upstreamed, and that the issue would be closed.   I wasn't really sure what the right way to share it was.
